// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_1002_BookTracking.Models;

#nullable disable

namespace WEB_1002_BookTracking.Migrations
{
    [DbContext(typeof(TrackingContext))]
    [Migration("20220817201147_IntialMigrations")]
    partial class IntialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("WEB_1002_BookTracking.Models.BookModel", b =>
                {
                    b.Property<int>("BookModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookModelId");

                    b.HasIndex("CategoryModelId");

                    b.ToTable("BookModels");
                });

            modelBuilder.Entity("WEB_1002_BookTracking.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryTypeModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryModelId");

                    b.HasIndex("CategoryTypeModelId");

                    b.ToTable("CategoryModels");
                });

            modelBuilder.Entity("WEB_1002_BookTracking.Models.CategoryTypeModel", b =>
                {
                    b.Property<int>("CategoryTypeModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryTypeModelId");

                    b.ToTable("CategoryTypeModels");
                });

            modelBuilder.Entity("WEB_1002_BookTracking.Models.BookModel", b =>
                {
                    b.HasOne("WEB_1002_BookTracking.Models.CategoryModel", "CategoryModel")
                        .WithMany()
                        .HasForeignKey("CategoryModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryModel");
                });

            modelBuilder.Entity("WEB_1002_BookTracking.Models.CategoryModel", b =>
                {
                    b.HasOne("WEB_1002_BookTracking.Models.CategoryTypeModel", "CategoryTypeModel")
                        .WithMany()
                        .HasForeignKey("CategoryTypeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryTypeModel");
                });
#pragma warning restore 612, 618
        }
    }
}
